# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: labeled_document.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='labeled_document.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16labeled_document.proto\"1\n\x08\x44ocument\x12\x13\n\x0b\x64ocument_id\x18\x01 \x02(\t\x12\x10\n\x08segments\x18\x02 \x03(\t\"\x17\n\x05Label\x12\x0e\n\x06logits\x18\x01 \x03(\x02\"5\n\x0fLabeledDocument\x12\x13\n\x0b\x64ocument_id\x18\x01 \x02(\t\x12\r\n\x05Label\x18\x02 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='document_id', full_name='Document.document_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segments', full_name='Document.segments', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=75,
)


_LABEL = _descriptor.Descriptor(
  name='Label',
  full_name='Label',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logits', full_name='Label.logits', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=100,
)


_LABELEDDOCUMENT = _descriptor.Descriptor(
  name='LabeledDocument',
  full_name='LabeledDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='document_id', full_name='LabeledDocument.document_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Label', full_name='LabeledDocument.Label', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['Document'] = _DOCUMENT
DESCRIPTOR.message_types_by_name['Label'] = _LABEL
DESCRIPTOR.message_types_by_name['LabeledDocument'] = _LABELEDDOCUMENT

Document = _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), dict(
  DESCRIPTOR = _DOCUMENT,
  __module__ = 'labeled_document_pb2'
  # @@protoc_insertion_point(class_scope:Document)
  ))
_sym_db.RegisterMessage(Document)

Label = _reflection.GeneratedProtocolMessageType('Label', (_message.Message,), dict(
  DESCRIPTOR = _LABEL,
  __module__ = 'labeled_document_pb2'
  # @@protoc_insertion_point(class_scope:Label)
  ))
_sym_db.RegisterMessage(Label)

LabeledDocument = _reflection.GeneratedProtocolMessageType('LabeledDocument', (_message.Message,), dict(
  DESCRIPTOR = _LABELEDDOCUMENT,
  __module__ = 'labeled_document_pb2'
  # @@protoc_insertion_point(class_scope:LabeledDocument)
  ))
_sym_db.RegisterMessage(LabeledDocument)


# @@protoc_insertion_point(module_scope)
